$ErrorActionPreference = "Stop"
$kitRoot = Split-Path -Parent $PSScriptRoot
$reposPath = Join-Path $kitRoot "config\repositories.json"
$globalAgents = Join-Path $kitRoot "source\global\AGENTS.md"
$commonPath = Join-Path $PSScriptRoot "lib\common.ps1"
. $commonPath

function Format-Rate([int]$Numerator, [int]$Denominator) {
  if ($Denominator -le 0) { return "N/A" }
  return ("{0:P2}" -f ($Numerator / [double]$Denominator))
}

$ruleVersion = "unknown"
if (Test-Path $globalAgents) {
  $meta = Get-RuleDocMetadata -Path $globalAgents
  if (-not [string]::IsNullOrWhiteSpace([string]$meta.version)) {
    $ruleVersion = [string]$meta.version
  }
}

$repos = Read-JsonArray $reposPath
$today = Get-Date -Format "yyyy-MM-dd"

foreach ($repoRaw in $repos) {
  $repo = Normalize-Repo ([string]$repoRaw)
  $repoWin = $repo -replace '/', '\'
  if (!(Test-Path $repoWin)) {
    Write-Host "[SKIP] repo not found: $repo"
    continue
  }

  $evidenceDir = Join-Path $repoWin "docs\change-evidence"
  $evidenceFiles = @()
  if (Test-Path $evidenceDir) {
    $evidenceFiles = @(Get-ChildItem -Path $evidenceDir -File -Filter *.md | Where-Object { $_.Name -ne "template.md" })
  }

  $required = @("规则ID","风险等级","执行命令","验证证据","回滚动作")
  $learningLoopRequired = @("learning_points_3","reusable_checklist","open_questions")
  $totalEvidence = $evidenceFiles.Count
  $completeEvidence = 0
  $learningLoopCompleteEvidence = 0
  foreach ($f in $evidenceFiles) {
    $kv = Parse-KeyValueFile $f.FullName
    $ok = $true
    foreach ($k in $required) {
      if (-not $kv.ContainsKey($k) -or [string]::IsNullOrWhiteSpace([string]$kv[$k])) { $ok = $false; break }
    }
    if ($ok) { $completeEvidence++ }

    $learningOk = $true
    foreach ($k in $learningLoopRequired) {
      if (-not $kv.ContainsKey($k) -or [string]::IsNullOrWhiteSpace([string]$kv[$k])) { $learningOk = $false; break }
    }
    if ($learningOk) { $learningLoopCompleteEvidence++ }
  }

  $waiverDir = Join-Path $repoWin "docs\governance\waivers"
  $waiverFiles = @()
  if (Test-Path $waiverDir) {
    $waiverFiles = @(Get-ChildItem -Path $waiverDir -File -Filter *.md | Where-Object { $_.Name -ne "_template.md" -and $_.Name -ne "waiver-template.md" })
  }

  $waiverActive = 0
  $waiverExpiredUnrecovered = 0
  $todayDate = (Get-Date).Date
  foreach ($f in $waiverFiles) {
    $kv = Parse-KeyValueFile $f.FullName
    $status = if ($kv.ContainsKey("status")) { ([string]$kv["status"]).ToLowerInvariant() } else { "" }
    $closed = $status -eq "closed" -or $status -eq "recovered" -or $status -eq "done"
    if (-not $closed) { $waiverActive++ }

    $expRaw = if ($kv.ContainsKey("expires_at")) { [string]$kv["expires_at"] } else { "" }
    $exp = Parse-IsoDate $expRaw
    if (-not $closed -and $null -ne $exp -and $exp.Date -lt $todayDate) {
      $waiverExpiredUnrecovered++
    }
  }

  $overdueRate = Format-Rate $waiverExpiredUnrecovered $waiverFiles.Count
  $evidenceRate = Format-Rate $completeEvidence $totalEvidence
  $learningLoopRate = Format-Rate $learningLoopCompleteEvidence $totalEvidence
  $metricsDir = Join-Path $repoWin "docs\governance"
  if (!(Test-Path $metricsDir)) {
    try {
      New-Item -ItemType Directory -Path $metricsDir -Force | Out-Null
    } catch {
      Write-Host "[WARN] cannot create metrics dir: $metricsDir"
      continue
    }
  }
  $metricsOut = Join-Path $metricsDir "metrics-auto.md"

  $content = @(
    "period=$today"
    "repo=$repo"
    "rule_version=$ruleVersion"
    "gate_pass_rate=N/A"
    "rollback_rate=N/A"
    "patch_recovery_overdue_rate=$overdueRate"
    "evidence_completeness_rate=$evidenceRate"
    "learning_loop_evidence_rate=$learningLoopRate"
    "waiver_active_count=$waiverActive"
    "waiver_expired_unrecovered_count=$waiverExpiredUnrecovered"
    "update_trigger_alert_count=N/A"
    "notes=auto-generated by governance-kit/scripts/collect-governance-metrics.ps1"
  ) -join "`r`n"

  try {
    Set-Content -Path $metricsOut -Value $content -Encoding UTF8
    Write-Host "[METRICS] $metricsOut"
  } catch {
    Write-Host "[WARN] cannot write metrics: $metricsOut"
  }
}

Write-Host "collect-governance-metrics done"
